### ISSUE TITLE
Add null safety support

### ISSUE THREAD

**Issue by minikin** [epam-cross-platform-lab/dart_result_type#4]
- Users want to use the package with `dart 2.12.0+` and `flutter 2.0.0+`

We need to add support for null safety.

**Comment by WorikQCI** [comment]
VSCode tells me:

```
The library 'package:result/result.dart' is legacy, and shouldn't be imported into a null safe library.
Try migrating the imported library.
```

when I include:
`import 'package:result/result.dart';`

In pubspec: `  result: ^1.0.4`

But here it is implied `result` is null safe now.
